### ISSUE TITLE
`ReferenceError: Symbol is not defined` on Node.js v0.10.40

### ISSUE THREAD

**Issue by idiotWu** [jayphelps/core-decorators.js#14]
When I import this module into my project and test the code on Node.js v0.10.40, it failed with error `ReferenceError: Symbol is not defined`, here's the result: https://travis-ci.org/idiotWu/observable/jobs/73702725.

I think you should use [`runtime` transformer](https://babeljs.io/docs/usage/runtime/) to fix this issue :)

**Comment by jayphelps** [comment]
I actually intentionally did not include any polyfills because the consuming app can choose to do so trivially; either global polyfills or if they're using Babel, they can certainly run core-decorators through their  Babel pipeline and include the `--optional runtime`. This is similar to how the test suite currently passes in Node v0.10.x because it includes the polyfill https://github.com/jayphelps/core-decorators.js/blob/master/package.json#L14.

While I prefer this policy for my libraries, this particular lib didn't really need to be using `for..of`, which causes the use of `Symbol`, so I refactored it out. Thanks for bringing to my attention!

**Comment by jayphelps** [comment]
Published to npm as `core-decorators@0.2.0`
