### ISSUE TITLE
browser version

### ISSUE THREAD

**Issue by zhakhalov** [jayphelps/core-decorators.js#43]
It would be grate to use this module in browser with single file output.

P.S.
How about publishing to bower?

**Comment by jayphelps** [comment]
I agree, basically just hasn't been done cause I don't need it and no one had requested it yet. :smile:

**Comment by jayphelps** [comment]
@zhakhalov now available via bower, you can also download it directly here https://github.com/jayphelps/core-decorators-artifacts

**Comment by jayphelps** [comment]
@zhakhalov btw just in case you hadn't heard, bower is almost certainly on its way out so I would consider alternatives (npm being the most obvious, combined with something _like_ webpack or browserify).

Also--isn't a bit weird to use decorators syntax...but not have the ability to import modules directly instead of globals? :trollface:
