### ISSUE TITLE
private & protected

### ISSUE THREAD

**Issue by wojtkowiak** [jayphelps/core-decorators.js#82]
Hey,

I do not know if you'd interested but I've released recently this https://github.com/wojtkowiak/private-decorator. 
It works only without `strict` because it is based on `function.caller` therefore you can use them only with `es2015-without-strict`.
If you want you can include it in your library. Of course you do not have to explain if you do not want to :smile: Just wanted you to know.

Greets

**Comment by jayphelps** [comment]
Very neat solution.

I don't think it belongs here because of the caveats you mentioned. Especially because ES2015 code is supposed to *always* be in strict mode implicitly which is why babel includes it by default.

> * Module code is always strict mode code.
> * All parts of a ClassDeclaration or a ClassExpression are strict mode code.

https://tc39.github.io/ecma262/#sec-strict-mode-code

This is important to note because not including it means you'll never be able to stop transpiling.
