### ISSUE TITLE
Unexpected token error in SyntaxErrorReporter

### ISSUE THREAD

**Issue by meilers** [jayphelps/core-decorators.js#90]
I'm trying to integrate the facebook library into my project and it uses core-decorators. However, I'm getting this error when I load the library:

![screen shot 2016-10-12 at 10 21 39 am](https://cloud.githubusercontent.com/assets/2792041/19320581/d4b81eac-907f-11e6-8544-fba603868601.png)

I'm using babel-preset-es2015 on stage 0. It seems that it doesn't like how the class fields are declared (without constructor). Anyway to fix this?

**Comment by jayphelps** [comment]
This is trying to use the code inside our src directory, which is untranspiled code. It should use the source inside lib instead or ideally rely on npm's module resolution for our `main` entry point.

You'll need to work with whoever is using core-decorators in this way to solve the issue. if you can let me know what facebook library you're using I can take a look as well.

**Comment by meilers** [comment]
Hi @jayphelps! Thanks for the quick response. I'm using [this facebook repo](https://www.npmjs.com/package/fb) that I'm adding to a react project that uses babel and webpack.

**Comment by jayphelps** [comment]
Okay, so it appears you're using `react-boilerplate`, which [adds `jsnext:main`](https://github.com/mxstbr/react-boilerplate/blob/0f88f55ed905f8432c3dd7b452d713df5fb76d8e/internals/webpack/webpack.base.babel.js#L92) as a module entry which links to our untranspiled `lib` directory.

I totally forgot that this was added, and it's likely never worked (it was meant for rollup in its early days) so I've since removed that field in my package.json and published core-decorators `0.13.0`.

Unfortunately, you'd need to wait until [facebook-node-sdk](https://github.com/node-facebook/facebook-node-sdk/blob/master/package.json#L31) upgrades their core-decorators version for you to receive those changes cause remember, this problem is caused by your boilerplate using `jsnext:main` and your dependency facebook-node-sdk including core-decorators which has a `jsnext:main` that doesn't work with webpack2. (confusing)

One thing you could _can_ try is is going into your boilerplate code and removing [`js:main` from your `mainFields` webpack config]((https://github.com/mxstbr/react-boilerplate/blob/0f88f55ed905f8432c3dd7b452d713df5fb76d8e/internals/webpack/webpack.base.babel.js#L92)). This might cause issues with _other_ dependencies though...

 ¯\_(ツ)_/¯ that's the best I can do on my end AFAICT.

**Comment by meilers** [comment]
Hi jay. Thanks for the help. I really appreciate it. I guess I'll just have to skip the facebook library for now and do ajax calls. Cheers!

**Comment by jayphelps** [comment]
@meilers best of luck! 🎉
