### ISSUE TITLE
react-native android error ?

### ISSUE THREAD

**Issue by trickymast3r** [jayphelps/core-decorators.js#91]
<img width="323" alt="screen shot 2016-10-24 at 09 00 00" src="https://cloud.githubusercontent.com/assets/5774210/19631559/547f56f4-99c8-11e6-980c-e0e76b3dee0e.png">

I got this error when try to run-android .
It's still work with run-ios .

**Comment by jayphelps** [comment]
Hard to know for sure just off that screenshot, but looks like it's erroring because there is no `Symbol.iterator` on Array. Try adding an ES2015 polyfill like [babel-polyfill](npmjs.com/package/babel-polyfill) or you can include the individual polyfills enough to bring your oldest platform up to ES2015 compliance.

**Comment by jayphelps** [comment]
Let me know if I can help further. Presumed fixed.
